Don't fail the build on formatting errors

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,12 +37,14 @@ jobs:
         guix pull -C channels.scm
         guix package -m manifest.scm
 
-    - name: Check C++ code formatting
+    - name: Check code formatting
       run: |
         set -euo pipefail
         guix shell -m manifest.scm -- sh <<'EOF'
           git ls-files --cached --others --exclude-standard -- '**/*.cpp' '**/*.hpp' \
-            | xargs clang-format --verbose --dry-run --Werror
+            | xargs clang-format --verbose --dry-run --Werror \
+            || echo "::warning::code formatting check failed."
+          fi
         EOF
 
     - name: Build & Test
