Fix formatting

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,13 +33,19 @@ jobs:
 
     - name: Install Dev Environment
       run: |
-        guix time-machine -C channels.scm -- package -m manifest.scm
+        set -euo pipefail
+        guix pull -C channels.scm
+        guix package -m manifest.scm
 
     - name: Check code formatting
       run: |
         guix shell -m manifest.scm -- sh <<'EOF'
-          git ls-files --cached --others --exclude-standard -- '**/*.cpp' '**/*.hpp' \
-              | xargs clang-format --verbose --dry-run --Werror
+          if ( ! git ls-files --cached --others --exclude-standard -- '**/*.cpp' '**/*.hpp' \
+              | xargs -r clang-format --verbose --dry-run --Werror )
+          then
+            echo "::warning::Code formatting check failed"
+            exit 1
+          fi
         EOF
       continue-on-error: true
 
